### ISSUE TITLE
Dropping piece does not work as expected

### ISSUE THREAD

**Issue by anitalakhadze** [atala15/hw2Tetris#7]
When trying to drop a piece, the piece stops just 1 or 2 blocks above the place it should land on. This might be related to [this](https://github.com/atala15/hw2Tetris/issues/4) issue.

**Comment by tornikeo** [comment]
I believe this was addressed in [this](https://github.com/atala15/hw2Tetris/commit/00361601be0f3d73213b159d193cf96b253b84a7) commit.
